const mockEvents = [
    {
        id: 1,
        eventName: "Sample Event 1",
        eventDate: "2023-12-15",
        eventTime: "9:00 AM",
        eventLocation: "Art’s Faculty",
        eventImage: require('../../assets/image.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
    {
        id: 2,
        eventName: "Sample Event 2",
        eventDate: "2023-12-15",
        eventTime: "9:00 AM",
        eventLocation: "Building 7",
        eventImage: require('../../assets/eventplaceholder.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
    {
        id: 3,
        eventName: "Sample Event 3",
        eventDate: "2024-01-20",
        eventTime: "9:00 AM",
        eventLocation: "Arts",
        eventImage: require('../../assets/eventplaceholder.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
    {
        id: 4,
        eventName: "Sample Event 4",
        eventDate: "2024-02-10",
        eventTime: "9:00 AM",
        eventLocation: "360",
        eventImage: require('../../assets/image.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
    {
        id: 5,
        eventName: "Sample Event 5",
        eventDate: "2024-03-05",
        eventTime: "9:00 AM",
        eventLocation: "IT",
        eventImage: require('../../assets/image.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
    {
        id: 6,
        eventName: "Sample Event 6",
        eventDate: "2024-04-15",
        eventTime: "9:00 AM",
        eventLocation: "Parma",
        eventImage: require('../../assets/image.png'),
        eventOrganizer: "John Doe",
        profileImage: require('../../assets/image 86.png'),
    },
];

export default mockEvents;