export const CREATE = 'CREATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_ID = 'FETCH_ID';
export const EDIT_ID = 'EDIT_ID';
export const CREATE_EVENT='CREATE_EVENT'
export const GETCONTACT='GETCONTACT'
export const CREATE_MESSAGE='CREATE_MESSAGE'
export const DELETE_MESSAGE='DELETE_MESSAGE'
export const EDIT_SUBJECT_ID='EDIT_SUBJECT_ID'
export const FETCH_ALL_SUBJECT='FETCH_ALL_SUBJECT'
export const ADD_SUBJECT_STUDENT='ADD_SUBJECT_STUDENT'


// Event User
export const MY_CREATED_EVENT='MY_CREATED_EVENT'
export const MY_JOINED_EVENTS='MY_JOINED_EVENTS'
export const JOIN_EVENT='JOIN_EVENT'
export const CHECK_IF_USER_JOINED_EVENT = 'CHECK_IF_USER_JOINED_EVENT'
export const LEAVE_EVENT = 'LEAVE_EVENT'

// auth
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

// club
export const FETCH_ALL_CLUBS='FETCH_ALL_CLUBS'
export const FETCH_ONE_CLUB='FETCH_ONE_CLUB'

// Club Events
export const FETCH_CLUB_EVENTS='FETCH_CLUB_EVENTS'

// Comment
export const CREATE_COMMENT='CREATE_COMMENT'
export const FETCH_COMMENTS='FETCH_COMMENTS'
export const DELETE_COMMENT='DELETE_COMMENT'
export const UPDATE_COMMENT='UPDATE_COMMENT'

// Friend
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const REJECT_FRIEND_REQUEST = 'REJECT_FRIEND_REQUEST';
export const SHOW_PENDING_REQUESTS = 'SHOW_PENDING_REQUESTS';
export const FETCH_FRIENDS_LIST = 'FETCH_FRIENDS_LIST';

// User
export const SHOW_PROFILE = 'SHOW_PROFILE';

// Event 
export const FETCH_ONE_EVENT = 'FETCH_ONE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';